import sgMail from '@sendgrid/mail';

if (!process.env.SENDGRID_API_KEY) {
  throw new Error("SENDGRID_API_KEY environment variable must be set");
}

sgMail.setApiKey(process.env.SENDGRID_API_KEY);

// You'll need to replace this with your verified sender email from SendGrid
const VERIFIED_SENDER = 'noreply@originality-meter.com'; // Replace with your verified sender

export interface EmailReportParams {
  recipientEmail: string;
  reportContent: string;
  reportTitle: string;
  analysisType: 'single' | 'comparison';
}

export async function sendReportEmail(params: EmailReportParams): Promise<boolean> {
  try {
    const { recipientEmail, reportContent, reportTitle, analysisType } = params;
    
    const subject = `Originality Analysis Report: ${reportTitle}`;
    
    // Create HTML email content
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>Originality Analysis Report</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
          .header { background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
          .content { background: white; padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
          .footer { margin-top: 20px; font-size: 12px; color: #666; text-align: center; }
          h1 { color: #2563eb; margin-bottom: 10px; }
          h2 { color: #1e40af; border-bottom: 2px solid #e5e7eb; padding-bottom: 5px; }
          .highlight { background: #fef3c7; padding: 2px 6px; border-radius: 4px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>🔍 Originality Analysis Report</h1>
          <p><strong>Report Title:</strong> ${reportTitle}</p>
          <p><strong>Analysis Type:</strong> ${analysisType === 'single' ? 'Single Passage Analysis' : 'Comparative Analysis'}</p>
          <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
        </div>
        
        <div class="content">
          ${reportContent.replace(/\n/g, '<br>')}
        </div>
        
        <div class="footer">
          <p>Generated by Originality Meter - Advanced AI-powered text analysis platform</p>
          <p>This report was automatically generated and sent to your email address.</p>
        </div>
      </body>
      </html>
    `;

    // Create plain text version
    const textContent = `
ORIGINALITY ANALYSIS REPORT
===========================

Report Title: ${reportTitle}
Analysis Type: ${analysisType === 'single' ? 'Single Passage Analysis' : 'Comparative Analysis'}
Generated: ${new Date().toLocaleString()}

${reportContent}

---
Generated by Originality Meter
Advanced AI-powered text analysis platform
    `;

    const msg = {
      to: recipientEmail,
      from: VERIFIED_SENDER,
      subject: subject,
      text: textContent,
      html: htmlContent,
    };

    await sgMail.send(msg);
    console.log(`Report email sent successfully to ${recipientEmail}`);
    return true;
  } catch (error) {
    console.error('SendGrid email error:', error);
    return false;
  }
}

export async function testSendGridConnection(): Promise<boolean> {
  try {
    // Test the API key by attempting to get account information
    const request = await fetch('https://api.sendgrid.com/v3/user/account', {
      headers: {
        'Authorization': `Bearer ${process.env.SENDGRID_API_KEY}`,
        'Content-Type': 'application/json'
      }
    });
    
    return request.ok;
  } catch (error) {
    console.error('SendGrid connection test failed:', error);
    return false;
  }
}